### ISSUE TITLE
Switch to time.Duration for backoff parameters?

### ISSUE THREAD

**Issue by daroot** [flowchartsman/retry#2]
Right now everything is hardcoded to use milliseconds, which is probably the most common use case, but it might be nice if instead you could pass in an arbitrary time.Duration.    I think this is probably more idiomatic, lets you do things like use the time package's Since/After and context.Deadline to set up retry durations and also lets you do delays that start at smaller amounts than a single millisecond.

**Comment by flowchartsman** [comment]
Yeah, I originally had it that way, but something made me decide to keep it to MS resolution. I'll try and get to it this week.

**Comment by flowchartsman** [comment]
Thanks for your contribution!
