### ISSUE TITLE
panic due to getnextBackoff() passing an unsupported backoff value to rand.Int63n

### ISSUE THREAD

**Issue by tadhunt** [flowchartsman/retry#4]
From the documentation of rand.Int63n (https://golang.org/src/math/rand/rand.go):

 	Int63n returns, as an int64, a non-negative pseudo-random number in [0,n).
 	It panics if n <= 0.

I just experienced this "invalid argument to Int63n" panic. It appears that given my initial conditions (initialDelay = 500 * time.Millisecond that "backoff" becomes negative on the 35th iteration, which leads to this panic.

You can reproduce with this testcase:

```golang
func TestBackoff(t *testing.T) {
	initialDelay := 500 * time.Millisecond
	maxDelay := 1 * time.Millisecond
	maxTries := 10000000 // a really big number

	attempts := 0
	operation := func(c context.Context) error {
		attempts++

		if attempts > 40 {
			return nil
		}
		log.Printf("TestBackoff: attempt %d", attempts)

		return fmt.Errorf("try again %d", attempts)
	}

	retrier := NewRetrier(maxTries, initialDelay, maxDelay)
	err := retrier.RunContext(context.Background(), operation)
	if err != nil {
		t.Errorf("%v", err)
	}
}
```

my fix is here: https://github.com/tadhunt/retry/commit/e5cb731d84742531b6904df9e0f39455a1270e86

**Comment by flowchartsman** [comment]
Closed by #5
